<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ModManager.FileApplier</AssemblyName>
    <RootNamespace>ModManager.FileApplier</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(ErosArtifactsDir)\ModManager\$(Configuration)\</OutputPath>
    <DebugType>portable</DebugType>
  </PropertyGroup>
</Project>
